### ISSUE TITLE
Question hows the progress going

### ISSUE THREAD

**Issue by SDUBZ** [Dragonoidzero/Azzys-Fruits#3]
1: is this gonna be very much like witchery 1 with wool spinnery etc ?
2: whats gonna be diff in this version ?
3: how long until you think you have a playable alpha ?

**Comment by MsRandom** [comment]
1: It's gonna be quite different in general, there will be a spinning wheel AFAIK if that is what you're referring to.
2: A lot, it's fundamentally different, only matching up in themes and concepts and *some* content, the base of the mod is going to be based on plant magic rather than altar magic.
3: There are currently no ETAs. The mod is being actively worked on, the first snapshot is quite close and it may end up taking from a few weeks to a bit longer.

Of course, only the owner can answer those accurately, which he will eventually. Those are all answers from my perspective from what I've been seeing.
If you're looking for something more like the original Witchery, there are other mods like that, such as Witchery: Resurrected which is a remake(although currently private on GitHub and only available on Discord), and Bewitchment which is a spiritual successor for Witchery.

**Comment by SDUBZ** [comment]
this is what i meant about spinning wool wheel https://ftbwiki.org/Spinning_Wheel_(Witchery)
do you happen to have links to the project or maybe the discord of Witchery: Resurrected  @MsRandom ?

**Comment by Azzyypaaras** [comment]
Ok. Firstly, I apologize for taking so long to answer this.

While I hold a lot of the concepts and ideas in witchery closely when it comes to the design and development of Forgotten Fruits, FF is not ultimately meant to be a direct port of witchery nor exactly a spiritual successor. Witchery is certainly a very large and very important inspiration that I aim to stay fairly faithful to, but FF also takes inspiration and ideas from other mods such as Thaumcraft and Chromaticraft. Most things from witchery will have their place in FF and their base ideas will likely stay the same (eg: the spirit/dream realm), but execution will ultimately differ.

While it is hard to say what will be different without revealing too many of my plans for the mod and also simply due to the early state of things, generally most things that were in the original witchery will stay relatively faithful. However, there are plans for significant expansions to the various branches of witchery and the addition of new ones altogether, and there are plans for full revamps of other things, such as the spirit realm.

As for when the first version will release. I am currently aiming for a release this weekend, most things required for that to happen are currently complete or close to being so, although there are a few things that may delay the first release (most notably, I would want to have REI support from the beginning). Lastly, it is important to note that the first will be relatively light, only containing the brewing system with most vanilla effects and a few unique ones (~15% of planned brew effects), the six basic/tier 1 plants, and a lot of groundwork for future versions. After the first version is out development should speed up a fair bit.

Lastly, https://discord.gg/y2EN7Uy
